//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMR00200BackResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PMR00200BackResourcesResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PMR00200BackResourcesResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMR00200BackResources.PMR00200BackResourcesResources_msgrsc", typeof(PMR00200BackResourcesResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOI Date.
        /// </summary>
        internal static string COLUMN_CREF_DATE {
            get {
                return ResourceManager.GetString("COLUMN_CREF_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOI No..
        /// </summary>
        internal static string COLUMN_CREF_NO {
            get {
                return ResourceManager.GetString("COLUMN_CREF_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman.
        /// </summary>
        internal static string COLUMN_CSALESMAN_ID_NAME {
            get {
                return ResourceManager.GetString("COLUMN_CSALESMAN_ID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string COLUMN_CTAX {
            get {
                return ResourceManager.GetString("COLUMN_CTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term &amp; Condition.
        /// </summary>
        internal static string COLUMN_CTC_MESSAGE {
            get {
                return ResourceManager.GetString("COLUMN_CTC_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        internal static string COLUMN_CTENANT_NAME {
            get {
                return ResourceManager.GetString("COLUMN_CTENANT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenure.
        /// </summary>
        internal static string COLUMN_CTENURE {
            get {
                return ResourceManager.GetString("COLUMN_CTENURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Name.
        /// </summary>
        internal static string COLUMN_CTRANS_NAME {
            get {
                return ResourceManager.GetString("COLUMN_CTRANS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Status.
        /// </summary>
        internal static string COLUMN_CTRANS_STATUS_NAME {
            get {
                return ResourceManager.GetString("COLUMN_CTRANS_STATUS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total Area.
        /// </summary>
        internal static string COLUMN_GRAND_TOT_AREA {
            get {
                return ResourceManager.GetString("COLUMN_GRAND_TOT_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string COLUMN_NTOTAL_COMMON_AREA_SIZE {
            get {
                return ResourceManager.GetString("COLUMN_NTOTAL_COMMON_AREA_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross.
        /// </summary>
        internal static string COLUMN_NTOTAL_GROSS_AREA_SIZE {
            get {
                return ResourceManager.GetString("COLUMN_NTOTAL_GROSS_AREA_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net.
        /// </summary>
        internal static string COLUMN_NTOTAL_NET_AREA_SIZE {
            get {
                return ResourceManager.GetString("COLUMN_NTOTAL_NET_AREA_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rent Price.
        /// </summary>
        internal static string COLUMN_NTOTAL_PRICE {
            get {
                return ResourceManager.GetString("COLUMN_NTOTAL_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string LABEL_CDEPARTMENT_NAME {
            get {
                return ResourceManager.GetString("LABEL_CDEPARTMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string LABEL_CPERIOD {
            get {
                return ResourceManager.GetString("LABEL_CPERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string LABEL_CPROPERTY_NAME {
            get {
                return ResourceManager.GetString("LABEL_CPROPERTY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman.
        /// </summary>
        internal static string LABEL_CSALESMAN_NAME {
            get {
                return ResourceManager.GetString("LABEL_CSALESMAN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total of Agreements.
        /// </summary>
        internal static string LABEL_GRAND_TOTAL_AGGR {
            get {
                return ResourceManager.GetString("LABEL_GRAND_TOTAL_AGGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outstanding Agreement Only.
        /// </summary>
        internal static string LABEL_LIS_OUTSTANDING {
            get {
                return ResourceManager.GetString("LABEL_LIS_OUTSTANDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Agreement Based On.
        /// </summary>
        internal static string LABEL_TOTAL_AGGR_BASED_ON {
            get {
                return ResourceManager.GetString("LABEL_TOTAL_AGGR_BASED_ON", resourceCulture);
            }
        }
    }
}
