//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMM07500FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PMM07500FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PMM07500FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMM07500FrontResources.PMM07500FrontResources_msgrsc", typeof(PMM07500FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string _btn_refresh {
            get {
                return ResourceManager.GetString("_btn_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        internal static string _label_effective_date {
            get {
                return ResourceManager.GetString("_label_effective_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _label_property {
            get {
                return ResourceManager.GetString("_label_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamp Rate.
        /// </summary>
        internal static string _label_stamp_rate {
            get {
                return ResourceManager.GetString("_label_stamp_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Amount may not be 0!.
        /// </summary>
        internal static string _val_stampamount1 {
            get {
                return ResourceManager.GetString("_val_stampamount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamp Amount may not be 0!.
        /// </summary>
        internal static string _val_stampamount2 {
            get {
                return ResourceManager.GetString("_val_stampamount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamp Code is required!.
        /// </summary>
        internal static string _val_stampcode1 {
            get {
                return ResourceManager.GetString("_val_stampcode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required!.
        /// </summary>
        internal static string _val_stampcode2 {
            get {
                return ResourceManager.GetString("_val_stampcode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Currency!.
        /// </summary>
        internal static string _val_stampcode3 {
            get {
                return ResourceManager.GetString("_val_stampcode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date is required!.
        /// </summary>
        internal static string _val_stampdate1 {
            get {
                return ResourceManager.GetString("_val_stampdate1", resourceCulture);
            }
        }
    }
}
