
--EXEC RSP_GS_GET_TRANS_CODE_INFO 'RCD','000000';
EXEC RSP_GL_GET_SYSTEM_PARAM 'rcd','en'
EXEC RSP_GS_GET_COMPANY_INFO 'BSI'
EXEC RSP_GL_GET_SYSTEM_ENABLE_OPTION_INFO 'rcd','GL014001'
EXEC RSP_GS_GET_GSB_CODE_LIST 'BIMASAKTI','RCD','_GL_JOURNAL_STATUS','en'

SELECT TOP 1 1 AS CRESULT
	FROM GSM_TRANSACTION_APPROVAL (NOLOCK)
	WHERE CCOMPANY_ID = 'BSI' 
	AND CDEPT_CODE = ''
	AND CUSER_ID = 'GHC' 
	AND CTRANS_CODE = '000000'

SELECT TOP 1 1 AS CRESULT
FROM GSM_TRANSACTION_APPROVAL (NOLOCK)
WHERE CCOMPANY_ID = 'BSI'
AND   CTRANS_CODE = '000000'
AND   (CDEPT_CODE       ='02' OR CDEPT_CODE='')
AND   CUSER_ID          ='vfm'

EXEC RSP_GL_GET_JOURNAL 'RCD','GHC','D43DD88B-9B65-4284-8819-FFC33206D31D','EN'
EXEC RSP_GS_GET_ALLOW_APPROVAL_STATUS 'RCD','000000','ACC','GHC' 


select * from GSM_TRANSACTION_APPROVAL

select * from gsm_goa_coa where cgoa_code in ('CASH', 'BANK')
EXEC RSP_GS_GET_GL_ACCOUNT_LIST 'rcd','','GLM00100','','',false,false,'ghc','','en',''
EXEC RSP_GS_GET_GL_ACCOUNT_LIST 'rcd','','GLM00101','','',false,false,'ghc','','en',''

EXEC RSP_GS_GET_GL_ACCOUNT_LIST 'rcd','','GLM00101','','',false,false,'ghc','','en',''
select * from gsm_goa_coa where CGOA_CODE in ('CASH','BANK')
and  ccompany_id='rcd'

EXEC RSP_GL_SEARCH_JOURNAL_LIST 'BSI','ghc','000000','02','202405','','','en'