EXEC RSP_GS_GET_PROPERTY_LIST 'RCD','ghc'

--EXEC RSP_LM_MAINTAIN_TENANT_CLASS_GRP 'RCD','ASHMD','TCG03','TCGNam3','ADD','GHC'
--EXEC RSP_LM_MAINTAIN_TENANT_CLASS_GRP  'RCD','ASHMD','TCG03','TCGNameeeee3','ADD','GHC'
--EXEC RSP_LM_MAINTAIN_TENANT_CLASS_GRP 'RCD','ASHMD','TCG03','TCGNam3','DELETE','GHC'

--EXEC RSP_LM_GET_TENANT_CLASS_GRP_LIST 'RCD','ASHMD','GHC'

--EXEC RSP_LM_GET_TENANT_CLASS_GRP_DETAIL   'RCD','ASHMD','TCG03','GHC'

