
SELECT p.name AS ParameterName, t.name AS ParameterType, p.max_length AS ParameterLength
FROM sys.parameters AS p
JOIN sys.types AS t ON t.user_type_id = p.user_type_id
WHERE object_id = OBJECT_ID('RSP_PM_GET_AGREEMENT_CHARGES_DISC_LIST')

delete from sat_locking where CUSER_ID= 'ghc' 

EXEC RSP_GS_GET_PROPERTY_LIST 'rcd','ghc'
SELECT CCODE, CDESCRIPTION FROM RFT_GET_GSB_CODE_INFO ('BIMASAKTI', 'rcd', '_BS_UNIT_CHARGES_TYPE', '', 'en')
EXEC RSP_GS_GET_PERIOD_DT_LIST 'rcd', '2024'
EXEC RSP_GS_GET_BUILDING_LIST 'rcd','ASHMD','ghc'

EXEC RSP_PM_GET_AGREEMENT_CHARGES_DISC_LIST 
'RCD' --company 
, 'ASHMD' --property
, '01' --charge type
, 'G002' --unit charges
, 'D001' --discount
, 'Daily Percentage' --Selected "Discount Type'
, '202401'
, 1
, 'TW-A'--building
, 'A'--agreement type
, 'ghc'--userid


CREATE TABLE #AGREEMENT_CHARGES_DISCOUNT
(	
	CCOMPANY_ID		VARCHAR(8)
, CPROPERTY_ID		VARCHAR(20)
, CREF_NO			VARCHAR(30)
, CSEQ_NO			VARCHAR(30)
, CFLOOR_ID		VARCHAR(30)
, CUNIT_ID		VARCHAR(30)
, CTENANT_ID		VARCHAR(30)
, NCHARGES_AMOUNT		VARCHAR(30)
, NCHARGE_DISCOUNT		VARCHAR(30)
, NNET_CHARGE		VARCHAR(30)
, CAGREEMENT_NO		VARCHAR(30)
, CSTART_DATE		VARCHAR(30)
, CEND_DATE		VARCHAR(30)
, CEXISTING_DISCOUNT_CODE	VARCHAR(30)
, NEXISTING_CHARGE_DISCOUNT	VARCHAR(30)
)

EXEC RSP_PM_PROCESS_AGREEMENT_CHARGE_DISCOUNT 
 'rcd'--'CCOMPANY_ID'			
, 'ASHMD'--'CPROPERTY_ID'
, 'refno1'-- 'CREF_NO		
, '202309'-- 'CREF_DATE			
, 'ct01'--'CCHARGES_TYPE		
, 'ch01'--'CCHARGES_ID			
, 'disc01'--'CDISCOUNT_CODE		
, '2024'--'CINV_PERIOD_YEAR		
, '09'--'CINV_PERIOD_MONTH	
, true--true --LALL_BUILDING
, 'TW-A1'--'CBUILDING_ID			
, 'cagrrtype'--'CAGREEMENT_TYPE		
, 'ADD'--'PROCESS		---untuk proces undo hanya mengganti bagian ini
, 'ghc'--'CUSER_ID
DROP TABLE #AGREEMENT_CHARGES_DISCOUNT