delete from sat_locking where CUSER_ID= 'admin'
EXEC RSP_GS_GET_PROPERTY_LIST 'rcd','en'
EXEC RSP_GS_GET_PERIOD_YEAR_RANGE 'RCD','',''
SELECT dbo.RFN_GET_DB_TODAY ('RCD')
EXEC RSP_GS_GET_PERIOD_DT_LIST 'RCD', '2023'
EXEC RSP_PMR00200_GET_REPORT
	'RCD'--@CCOMPANY_ID	
	, 'ASHMD'--@CPROPERTY_ID	
	, 'ACC'--@CFROM_DEPARTMENT_ID	
	, 'FIN'--@CTO_DEPARTMENT_ID
	, 'C098'--@CFROM_SALESMAN_ID
	, 'TEST02'	--@CTO_SALESMAN_ID
	, '202404'--@CFROM_PERIOD	
	, '202406'--@CTO_PERIOD	
	, ''--@LIS_OUTSTANDING
	, 'EN'--@CLANG_ID	
		
	delete from sat_locking where CUSER_ID= 'ghc' 

	
		
		
		
		
			